### ISSUE TITLE
Error if there is not "name" field on user model

### ISSUE THREAD

**Issue by alextime** [launcher-host/mercurius#28]
Error if there is no "name" field on user model.

Is it possible to override the name field based on ConversationRepository? I our installation there is no "name" field but "first_name" plus "last_..." etc, maybe could be useful if we can override that field that there is hard coded on that repo right now. Actually I have no idea on how to override...

**Comment by akazorg** [comment]
Hi @alextime, thanks for your message, we will definitely update Mercurius in order to support that. 

That change will affect mostly the `ConversationRepository`, but several other files require revision and there's no straightforward solution for now.

I've added #29 feature to extend users model.
